MusicLibrary/Models/ErrorViewModel.cs
using System;

namespace MusicLibrary.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MusicLibrary/ViewModels/AlbumPhotosVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicLibrary.ViewModels
{
    public class AlbumPhotosVM
    {
        public string UrlPhoto { get; set; }
        public string Title { get; set; }
        public int Id { get; set; }
    }
}

MusicLibrary/ViewModels/AlbumsVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicLibrary.ViewModels
{
    public class AlbumsVM
    {
        public string Title { get; set; }
        public int Id { get; set; }
    }
}

MusicLibrary/ViewModels/CommentsVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicLibrary.ViewModels
{
    public class CommentsVM
    {
        public string name { get; set; }
        public string body { get; set; }
    }
}

MusicLibrary/Controllers/AlbumsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MusicLibrary.DTO;
using MusicLibrary.ViewModels;
using MusicService.DTO;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;


namespace MusicLibrary.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly IOptions<DTO.MusicMicroService> _config;

        public AlbumsController(IOptions<DTO.MusicMicroService> config)
        {
            _config = config;
        }

        // GET: Albums

        public async Task<ActionResult> Index()
        {
            using (HttpClient client = new HttpClient())
            {
                string Albums = await client.GetStringAsync($"{_config.Value.AlbumUrl}/GetAll");
                var ListAlbums = Newtonsoft.Json.JsonConvert.DeserializeObject<List<AlbumsVM>>(Albums);
                return View(ListAlbums);

            }
        }

        public async Task<List<AlbumPhotosVM>> AlbumPhotos(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                string AlbumsPhotos = await client.GetStringAsync($"{_config.Value.PhotosUrl}/AlbumPhotos?id={id}");
                var ListAlbums = Newtonsoft.Json.JsonConvert.DeserializeObject<List<AlbumPhotosVM>>(AlbumsPhotos);
                return ListAlbums;

            }
        }

        public async Task<List<CommentsVM>> PhotoComments(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                string PhotosComment = await client.GetStringAsync($"{_config.Value.CommentsUrl}/PhotoComments?id={id}");
                var ListComments = Newtonsoft.Json.JsonConvert.DeserializeObject<List<CommentsVM>>(PhotosComment);
                return ListComments;

            }
        }





    }
}

MusicLibrary/Views/Albums/Index.cshtml
@model IEnumerable<MusicLibrary.ViewModels.AlbumsVM>

@{
    ViewData["Title"] = "Index";
}
<h1>Albums</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    <a class="btn btn-success" style="color: white;" data-toggle="collapse" data-target="#collapse-@item.Id" onclick="GetPhotoAlbums(@item.Id)" role="button" aria-expanded="false" aria-controls="collapse-@item.Id">
                        Ver álbum
                    </a>
                </td>
            </tr>
            <tr>
                <td style="padding:0px !important;">
                    <div class="collapse" id="collapse-@item.Id"></div>
                </td>
            </tr>
        }
    </tbody>
</table>


@await Html.PartialAsync("~/Views/CommentsModal.cshtml");



MusicLibrary/Views/CommentsModal.cshtml
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Comentarios</h4>
            </div>
            <div class="modal-body" id="bodycomments">
              
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>

    </div>
</div>


MusicLibrary/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MusicLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicLibrary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/Albums.js"></script>
</head>


<body>
    <header style="background-color:#1DB954">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" >
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: white; font-weight: bold;">Music Library</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Albums" asp-action="Index" style=" font-weight: bold;">Albums</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MusicLibrary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>
